### ISSUE TITLE
Plugin does not capture images

### ISSUE THREAD

**Issue by ahelmel** [sudharsan-selvaraj/protractor-screenshot-utils#3]
A very nice plugin, but unfortunately it does not capture images.

The avatar in the header is missing in the screenshot, see "home--protractor-screenshot-utils.png". (screenshot 1) When made the screenshot with protractor browser the image is visible, see "home--protractor-browser.png" (screenshot 2).

![home--protractor-screenshot-utils](https://user-images.githubusercontent.com/756820/72688924-56cad080-3b0c-11ea-90ff-fe080976c7ff.png)

![home--protractor-browser](https://user-images.githubusercontent.com/756820/72688928-60eccf00-3b0c-11ea-8141-ac6da31b9af8.png)

**Comment by saikris12** [comment]
I have the same issue with the plugin. Looking at the code, images seem to be ignored explicitly. 

`base64String = base64String.replace(/^data:image\/png;base64,/, "");`

@sudharsan-selvaraj  Any specific reason for this? 

**Update**: After digging into the code, I was able to fix the image issue. 

The util uses html2canvas which has an issue with loading cross-origin images. We have to use a proxy to get over this issue. This is a great little proxy that can be used : https://github.com/niklasvh/html2canvas-proxy/

You need to update the injection script in index.ts code as below: 

`html2canvas(arguments[0],{letterRendering: 1,allowTaint: false, proxy: "http://localhost:3000",}).then(function(canvas)`

The url http://locahost:3000 corresponds to the node proxy running on port 3000. 

You can use below script to start the node proxy : 

https://gist.github.com/saikris12/f3cf0ef92b9c60b9e4dccf89e218b79b

**Comment by sudharsan-selvaraj** [comment]
@saikris12  The issue with cross-origin images is fixed by passing `{useCors: true}` option to html2canvas object. i tested it with several webpages and it seems to be working fine. In case if you are facing the CORS issue, feel free to open a new issue and we can tackle it separately.

**Comment by saikris12** [comment]
> @saikris12 The issue with cross-origin images is fixed by passing `{useCors: true}` option to html2canvas object. i tested it with several webpages and it seems to be working fine. In case if you are facing the CORS issue, feel free to open a new issue and we can tackle it separately.

useCors: true does not work unless the header is set on the server side which is hard to do incase the images are hosted on AWS S3 buckets which is my case. The proxy solution I mentioned above works though.
